const animals = [
  {
    id: 'Eagle',
    name: 'Eagle',
    title: 'West End Bald Eagle',
    region: 'on an island near Los Angeles',
    population: 'more than 270 pairs in 2013',
    habitat: 'Typically nest in forested areas adjacent to large bodies of water',
    diet:
      'Main live prey consists of medium sized mammals and birds such as rabbits, hares, grouse and ptarmigan. The diet of coastal birds includes gulls and other seabirds.р',
    src: 'assets/images/pet-cards/eagle.png',
    href: '#',
    country: 'US',
    videos: [
      'https://www.youtube.com/embed/hTfbB02IRLQ',
      'https://www.youtube.com/embed/7utMaDb1W08',
      'https://www.youtube.com/embed/XfoUF8YkB7A',
    ],
    descriptions: ['Population', 'habitat', 'diet'],
    pinY: 21,
    pinX: 12,
  },
  {
    id: 'Panda',
    name: 'Panda',
    title: 'Flexing panda',
    region: 'on an island near Los Angeles',
    population: 'About 1,590 individuals',
    habitat: 'Temperate forests high in the mountains of southwest China',
    diet:
      "A panda's daily diet consists almost entirely of the leaves, stems and shoots of various bamboo species. Bamboo contains very little nutritional value so pandas must eat 12-38kg every day to meet their energy needs.",
    src: 'assets/images/pet-cards/panda.png',
    href: '#',
    country: 'CN',
    videos: [
      'https://www.youtube.com/embed/OObOQ2GElhA',
      'https://www.youtube.com/embed/D0eqnda8dOk',
      'https://www.youtube.com/embed/65JHo3Cy2tY',
    ],
    descriptions: ['Population', 'habitat', 'diet'],
    pinY: 24,
    pinX: 74,
  },
  {
    id: 'Alligator',
    name: 'Alligator',
    title: 'Alligator and Spoonbill Swamp',
    region: 'on an island near Los Angeles',
    population: 'more than 270 pairs in 2013',
    habitat: 'Alligators can be found in slow-moving rivers, ponds, lakes and swamps.',
    diet:
      'Their diets include prey species that are abundant and easily accessible. Juvenile alligators eat primarily insects, amphibians, small fish, and other invertebrates. Adult alligators eat rough fish, snakes, turtles, small mammals, and birds.',
    src: 'assets/images/pet-cards/alligator.png',
    href: '#',
    country: 'US',
    videos: [
      'https://www.youtube.com/embed/X5Im4mMFK4A',
      'https://www.youtube.com/embed/uYEO1GDxsc4',
      'https://www.youtube.com/embed/nJCk-4Ojqaw',
    ],
    descriptions: ['Population', 'habitat', 'diet'],
    pinY: 26,
    pinX: 21.8,
  },
  {
    id: 'Gorilla',
    name: 'Gorilla',
    title: 'Grace Gorilla Forest Corridor',
    region: 'on an island near Los Angeles',
    population: 'more than 270 pairs in 2013',
    habitat:
      'Gorillas primarily inhabit tropical forest habitats.Tropical forests are characterized as having little variance in temperature (around 23°C) and length of daylight (around 12 hours).',
    diet:
      'Gorillas stick to a mainly vegetarian diet, feeding on stems, bamboo shoots and fruits. Western lowland gorillas, however, also have an appetite for termites and ants, and break open termite nests to eat the larvae.',
    src: 'assets/images/pet-cards/gorilla.png',
    href: '#',
    country: 'CM',
    videos: [
      'https://www.youtube.com/embed/672cUSe69J0',
      'https://www.youtube.com/embed/ARpl5ffDhiI',
      'https://www.youtube.com/embed/rgXWDk7rh4w',
    ],
    descriptions: ['Population', 'habitat', 'diet'],
    pinY: 40,
    pinX: 48,
  },
  {
    id: 'Fox',
    name: 'Fox',
    title: 'Flexing fox',
    region: 'on an island near Los Angeles',
    population: 'more than 270 pairs in 2013',
    habitat:
      'Gorillas primarily inhabit tropical forest habitats.Tropical forests are characterized as having little variance in temperature (around 23°C) and length of daylight (around 12 hours).',
    diet:
      'Gorillas stick to a mainly vegetarian diet, feeding on stems, bamboo shoots and fruits. Western lowland gorillas, however, also have an appetite for termites and ants, and break open termite nests to eat the larvae.',
    src: 'assets/images/pet-cards/fox.png',
    href: '#',
    country: 'US',
    videos: [
      'https://www.youtube.com/embed/hTfbB02IRLQ',
      'https://www.youtube.com/embed/7utMaDb1W08',
      'https://www.youtube.com/embed/XfoUF8YkB7A',
    ],
    descriptions: ['Population', 'habitat', 'diet'],
  },
  {
    id: 'Koala',
    name: 'Koala',
    title: 'Lazy koala',
    region: 'on an island near Los Angeles',
    population: 'more than 270 pairs in 2013',
    habitat:
      'Gorillas primarily inhabit tropical forest habitats.Tropical forests are characterized as having little variance in temperature (around 23°C) and length of daylight (around 12 hours).',
    diet:
      'Gorillas stick to a mainly vegetarian diet, feeding on stems, bamboo shoots and fruits. Western lowland gorillas, however, also have an appetite for termites and ants, and break open termite nests to eat the larvae.',
    src: 'assets/images/pet-cards/koala.png',
    href: '#',
    country: 'US',
    videos: [
      'https://www.youtube.com/embed/X5Im4mMFK4A',
      'https://www.youtube.com/embed/uYEO1GDxsc4',
      'https://www.youtube.com/embed/nJCk-4Ojqaw',
    ],
    descriptions: ['Population', 'habitat', 'diet'],
  },
  {
    id: 'Elephant',
    name: 'Elephant',
    title: 'Really big Elephant',
    region: 'on an island near Los Angeles',
    population: 'more than 270 pairs in 2013',
    habitat:
      'Gorillas primarily inhabit tropical forest habitats.Tropical forests are characterized as having little variance in temperature (around 23°C) and length of daylight (around 12 hours).',
    diet:
      'Gorillas stick to a mainly vegetarian diet, feeding on stems, bamboo shoots and fruits. Western lowland gorillas, however, also have an appetite for termites and ants, and break open termite nests to eat the larvae.',
    src: 'assets/images/pet-cards/elephant.png',
    href: '#',
    country: 'CM',
    videos: [
      'https://www.youtube.com/embed/672cUSe69J0',
      'https://www.youtube.com/embed/ARpl5ffDhiI',
      'https://www.youtube.com/embed/rgXWDk7rh4w',
    ],
    descriptions: ['Population', 'habitat', 'diet'],
  },
  {
    id: 'Tiger',
    name: 'Tiger',
    title: 'Angry tiger',
    region: 'on an island near Los Angeles',
    population: 'About 1,590 individuals',
    habitat: 'Temperate forests high in the mountains of southwest China',
    diet:
      "A panda's daily diet consists almost entirely of the leaves, stems and shoots of various bamboo species. Bamboo contains very little nutritional value so pandas must eat 12-38kg every day to meet their energy needs.",
    src: 'assets/images/pet-cards/tiger.png',
    href: '#',
    country: 'CN',
    videos: [
      'https://www.youtube.com/embed/OObOQ2GElhA',
      'https://www.youtube.com/embed/D0eqnda8dOk',
      'https://www.youtube.com/embed/65JHo3Cy2tY',
    ],
    descriptions: ['Population', 'habitat', 'diet'],
  },
];

export default animals;
